//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalProjesi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalDBEntities1 : DbContext
    {
        public CarRentalDBEntities1()
            : base("name=CarRentalDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Car> tbl_Car { get; set; }
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<tbl_Person> tbl_Person { get; set; }
        public virtual DbSet<tbl_RentedCar> tbl_RentedCar { get; set; }
        public virtual DbSet<tbl_RentedCarr> tbl_RentedCarr { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
