//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Company
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyAddress { get; set; }
        public int CarCount { get; set; }
        public int CompanyPoint { get; set; }
    }
}
