//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Car
    {
        public int CarID { get; set; }
        public string CarName { get; set; }
        public string CarModel { get; set; }
        public int DriverLisenseAge { get; set; }
        public int MinimumAgeLimit { get; set; }
        public int DailyKmLimit { get; set; }
        public int CurrentKm { get; set; }
        public Nullable<bool> Airbag { get; set; }
        public int BaggageCapacity { get; set; }
        public int SeatCount { get; set; }
        public int DailyRentalPrice { get; set; }
    }
}
