//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RentedCarr
    {
        public int RentedID { get; set; }
        public System.DateTime RentDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public bool IsRented { get; set; }
        public int Price { get; set; }
        public int CustomerID { get; set; }
    }
}
